apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-udd
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-udd
  template:
    metadata:
      labels:
        app: poc-udd
    spec:
      containers:
      - name: poc-udd
        image: jhidalgoc/poc-udd:latest
---
apiVersion: v1
kind: Service
metadata:
  name: poc-udd
  namespace: poc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    name: poc-udd-port
  selector:
    app: poc-udd

