kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-nfs-pvc
  namespace: poc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: jhidalgoc/mssql:latest
        lifecycle:
          postStart:
            exec:
              command: ["/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P4ssw0rd", "-Q", "CREATE DATABASE demo ON (FILENAME=N'/data/demo.mdf'),  (FILENAME=N'/data/demo.ldf') FOR ATTACH"]
        volumeMounts:
        - name: mssql-nfs-pvc
          mountPath: /data
        livenessProbe:
          exec:
            command: ["/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P4ssw0rd", "-Q", "SELECT 1"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P4ssw0rd", "-Q", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mssql-nfs-pvc
        persistentVolumeClaim:
          claimName: mssql-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: poc
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql-port
  selector:
    app: mssql

