kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-nfs-pvc
  namespace: poc
  labels:
    app: movies-bd
    vesion: v1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: poc
  labels:
    app: movies-bd
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-bd
      version: v1
  template:
    metadata:
      labels:
        app: movies-bd
        version: v1
    spec:
      containers:
      - name: mssql
        image: jhidalgoc/mssql:latest
        securityContext:
          privileged: true        
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: ["/opt/scripts/install_and_test_bd.sh"]
        volumeMounts:
        - name: mssql-nfs-pvc
          mountPath: /data
        livenessProbe:
          exec:
            command: ["/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P4ssw0rd", "-Q", "SELECT 1"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            #command: ["/bin/sh"]
            command: ["/bin/sh", "/opt/scripts/install_and_test_bd.sh"]
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mssql-nfs-pvc
        persistentVolumeClaim:
          claimName: mssql-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: poc
  labels:
    app: movies-bd
    version: v1
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    name: tcp-1433
  selector:
    app: movies-bd

