kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-nfs-pvc
  namespace: poc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: jhidalgoc/mssql:latest
        securityContext:
            privileged: true
        volumeMounts:
        - name: mssql-nfs-pvc
          mountPath: /data
      volumes:
      - name: mssql-nfs-pvc
        persistentVolumeClaim:
          claimName: mssql-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: poc
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql-port
  selector:
    app: mssql

